/* ============================================================
   APEX — Motor de Programação v2 · Passo 1
   Base de exercícios estruturada (~125). Ver
   referencia/MOTOR-V2-ESPECIFICACAO.md (secção 3.1).

   Contagem fracionada (spec 2.1): primário = 1.0, secundário = 0.5.
   `padrao` herda de FAMILIA_PADRAO salvo indicação explícita.
   ============================================================ */

import {
  FAMILIA_PADRAO,
  type ContributoPrimario,
  type ContributoSecundario,
  type Exercicio,
  type Musculo,
  type Padrao,
} from "./tipos.ts";

const P = (m: Musculo): ContributoPrimario => ({ musculo: m, contributo: 1.0 });
const S = (m: Musculo): ContributoSecundario => ({ musculo: m, contributo: 0.5 });

type EntradaExercicio = Omit<Exercicio, "padrao"> & { padrao?: Padrao };
const ex = (e: EntradaExercicio): Exercicio => ({
  ...e,
  padrao: e.padrao ?? FAMILIA_PADRAO[e.familia],
});

export const EXERCICIOS: Exercicio[] = [
  // =========================================================================
  // SQUAT — agachar (alternativas entre si)
  // =========================================================================
  ex({
    id: "agachamento_barra_costas",
    nome: "Agachamento com barra (costas)",
    familia: "squat",
    tier: 1,
    primarios: [P("quadriceps"), P("gluteo")],
    secundarios: [S("adutores"), S("isquiotibiais"), S("lombar"), S("core")],
    fadigaSistemica: 3,
    fadigaLocal: 3,
    exigenciaTecnica: 3,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["barra"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["joelho", "lombar", "anca"],
    progressao: "alta",
  }),
  ex({
    id: "agachamento_frontal",
    nome: "Agachamento frontal",
    familia: "squat",
    tier: 1,
    primarios: [P("quadriceps")],
    secundarios: [S("gluteo"), S("core"), S("lombar"), S("adutores")],
    fadigaSistemica: 3,
    fadigaLocal: 3,
    exigenciaTecnica: 3,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["barra"],
    nivelMinimo: "avancado",
    contraindicacoes: ["joelho", "pulso", "lombar"],
    progressao: "alta",
  }),
  ex({
    id: "agachamento_goblet",
    nome: "Agachamento goblet",
    familia: "squat",
    tier: 2,
    primarios: [P("quadriceps"), P("gluteo")],
    secundarios: [S("core"), S("adutores")],
    fadigaSistemica: 2,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["halteres", "kettlebell"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["joelho"],
    progressao: "media",
  }),
  ex({
    id: "agachamento_smith",
    nome: "Agachamento no Smith",
    familia: "squat",
    tier: 2,
    primarios: [P("quadriceps"), P("gluteo")],
    secundarios: [S("adutores"), S("isquiotibiais")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 1,
    estabilidade: "apoiado",
    perfilResistencia: "medio",
    equipamento: ["maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["joelho", "lombar"],
    progressao: "alta",
  }),
  ex({
    id: "hack_squat_maquina",
    nome: "Hack squat (máquina)",
    familia: "squat",
    tier: 2,
    primarios: [P("quadriceps")],
    secundarios: [S("gluteo"), S("adutores")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "alongado",
    equipamento: ["maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["joelho"],
    progressao: "alta",
  }),
  ex({
    id: "prensa_pernas_45",
    nome: "Prensa de pernas 45°",
    familia: "squat",
    tier: 2,
    primarios: [P("quadriceps"), P("gluteo")],
    secundarios: [S("adutores"), S("isquiotibiais")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "medio",
    equipamento: ["maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["joelho", "lombar"],
    progressao: "alta",
  }),
  ex({
    id: "cadeira_extensora",
    nome: "Cadeira extensora",
    familia: "squat",
    padrao: "agachar",
    tier: 3,
    primarios: [P("quadriceps")],
    secundarios: [],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "encurtado",
    equipamento: ["maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["joelho"],
    progressao: "media",
  }),

  // =========================================================================
  // HINGE — dobrar a anca
  // =========================================================================
  ex({
    id: "terra_convencional",
    nome: "Levantamento terra convencional",
    familia: "hinge",
    tier: 1,
    primarios: [P("isquiotibiais"), P("gluteo")],
    secundarios: [S("lombar"), S("dorsais"), S("trapezio_superior"), S("quadriceps"), S("antebraco"), S("core")],
    fadigaSistemica: 3,
    fadigaLocal: 3,
    exigenciaTecnica: 3,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["barra"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["lombar", "anca"],
    progressao: "alta",
  }),
  ex({
    id: "terra_sumo",
    nome: "Levantamento terra sumo",
    familia: "hinge",
    tier: 1,
    primarios: [P("gluteo"), P("quadriceps")],
    secundarios: [S("adutores"), S("isquiotibiais"), S("lombar"), S("dorsais"), S("antebraco")],
    fadigaSistemica: 3,
    fadigaLocal: 3,
    exigenciaTecnica: 3,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["barra"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["lombar", "anca", "joelho"],
    progressao: "alta",
  }),
  ex({
    id: "terra_trap_bar",
    nome: "Levantamento terra na trap-bar",
    familia: "hinge",
    tier: 1,
    primarios: [P("quadriceps"), P("isquiotibiais")],
    secundarios: [S("gluteo"), S("lombar"), S("trapezio_superior"), S("antebraco"), S("core")],
    fadigaSistemica: 3,
    fadigaLocal: 3,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["barra"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["lombar", "anca"],
    progressao: "alta",
  }),
  ex({
    id: "rdl_barra",
    nome: "Peso morto romeno com barra",
    familia: "hinge",
    tier: 2,
    primarios: [P("isquiotibiais"), P("gluteo")],
    secundarios: [S("lombar"), S("dorsais"), S("antebraco")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["barra"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["lombar"],
    progressao: "alta",
  }),
  ex({
    id: "rdl_halteres",
    nome: "Peso morto romeno com halteres",
    familia: "hinge",
    tier: 2,
    primarios: [P("isquiotibiais"), P("gluteo")],
    secundarios: [S("lombar"), S("antebraco")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["halteres"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["lombar"],
    progressao: "media",
  }),
  ex({
    id: "good_morning",
    nome: "Good morning",
    familia: "hinge",
    tier: 2,
    primarios: [P("isquiotibiais")],
    secundarios: [S("lombar"), S("gluteo"), S("core")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 3,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["barra"],
    nivelMinimo: "avancado",
    contraindicacoes: ["lombar", "anca"],
    progressao: "media",
  }),
  ex({
    id: "hip_hinge_maquina",
    nome: "Peso morto na máquina (hip hinge)",
    familia: "hinge",
    tier: 2,
    primarios: [P("isquiotibiais"), P("gluteo")],
    secundarios: [S("lombar")],
    fadigaSistemica: 1,
    fadigaLocal: 3,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "medio",
    equipamento: ["maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["lombar"],
    progressao: "alta",
  }),
  ex({
    id: "pull_through_cabo",
    nome: "Pull-through no cabo",
    familia: "hinge",
    tier: 3,
    primarios: [P("gluteo")],
    secundarios: [S("isquiotibiais"), S("core")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "encurtado",
    equipamento: ["cabos"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),

  // =========================================================================
  // UNILATERAL INFERIOR
  // =========================================================================
  ex({
    id: "agachamento_bulgaro_halteres",
    nome: "Agachamento búlgaro com halteres",
    familia: "unilateral_inferior",
    tier: 2,
    primarios: [P("quadriceps"), P("gluteo")],
    secundarios: [S("adutores"), S("isquiotibiais"), S("core")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["halteres"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["joelho"],
    progressao: "media",
  }),
  ex({
    id: "agachamento_bulgaro_barra",
    nome: "Agachamento búlgaro com barra",
    familia: "unilateral_inferior",
    tier: 2,
    primarios: [P("quadriceps"), P("gluteo")],
    secundarios: [S("adutores"), S("isquiotibiais"), S("core"), S("lombar")],
    fadigaSistemica: 3,
    fadigaLocal: 3,
    exigenciaTecnica: 3,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["barra"],
    nivelMinimo: "avancado",
    contraindicacoes: ["joelho", "lombar"],
    progressao: "media",
  }),
  ex({
    id: "afundo_passo_atras",
    nome: "Afundo com passo atrás",
    familia: "unilateral_inferior",
    tier: 2,
    primarios: [P("quadriceps"), P("gluteo")],
    secundarios: [S("isquiotibiais"), S("adutores"), S("core")],
    fadigaSistemica: 2,
    fadigaLocal: 2,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["halteres", "barra"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["joelho"],
    progressao: "media",
  }),
  ex({
    id: "afundo_caminhado",
    nome: "Afundo caminhado",
    familia: "unilateral_inferior",
    tier: 2,
    primarios: [P("quadriceps"), P("gluteo")],
    secundarios: [S("isquiotibiais"), S("adutores"), S("core")],
    fadigaSistemica: 3,
    fadigaLocal: 3,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["halteres", "barra"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["joelho"],
    progressao: "media",
  }),
  ex({
    id: "step_up_caixa",
    nome: "Step-up à caixa",
    familia: "unilateral_inferior",
    tier: 3,
    primarios: [P("quadriceps"), P("gluteo")],
    secundarios: [S("isquiotibiais"), S("core")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "encurtado",
    equipamento: ["halteres", "caixa"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["joelho"],
    progressao: "media",
  }),
  ex({
    id: "hack_squat_1_perna",
    nome: "Agachamento a 1 perna na máquina",
    familia: "unilateral_inferior",
    tier: 3,
    primarios: [P("quadriceps"), P("gluteo")],
    secundarios: [S("adutores")],
    fadigaSistemica: 1,
    fadigaLocal: 3,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "alongado",
    equipamento: ["maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["joelho"],
    progressao: "alta",
  }),
  ex({
    id: "pistol_squat",
    nome: "Pistol squat",
    familia: "unilateral_inferior",
    tier: 3,
    primarios: [P("quadriceps"), P("gluteo")],
    secundarios: [S("core"), S("adutores"), S("isquiotibiais")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 3,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["peso_corporal"],
    nivelMinimo: "avancado",
    contraindicacoes: ["joelho", "tornozelo"],
    progressao: "baixa",
  }),

  // =========================================================================
  // KNEE FLEXION — isquiotibiais
  // =========================================================================
  ex({
    id: "curl_femoral_deitado",
    nome: "Curl femoral deitado (máquina)",
    familia: "knee_flexion",
    tier: 3,
    primarios: [P("isquiotibiais")],
    secundarios: [S("gemeos")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "medio",
    equipamento: ["maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),
  ex({
    id: "curl_femoral_sentado",
    nome: "Curl femoral sentado (máquina)",
    familia: "knee_flexion",
    tier: 3,
    primarios: [P("isquiotibiais")],
    secundarios: [S("gemeos")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "alongado",
    equipamento: ["maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),
  ex({
    id: "curl_femoral_em_pe_cabo",
    nome: "Curl femoral em pé no cabo",
    familia: "knee_flexion",
    tier: 3,
    primarios: [P("isquiotibiais")],
    secundarios: [],
    fadigaSistemica: 1,
    fadigaLocal: 1,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "encurtado",
    equipamento: ["cabos", "maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),
  ex({
    id: "nordic_curl",
    nome: "Curl nórdico",
    familia: "knee_flexion",
    tier: 2,
    primarios: [P("isquiotibiais")],
    secundarios: [S("gemeos"), S("core")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 3,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["peso_corporal"],
    nivelMinimo: "avancado",
    contraindicacoes: ["joelho"],
    progressao: "baixa",
  }),

  // =========================================================================
  // HIP EXTENSION — glúteo
  // =========================================================================
  ex({
    id: "hip_thrust_barra",
    nome: "Hip thrust com barra",
    familia: "hip_extension",
    tier: 2,
    primarios: [P("gluteo")],
    secundarios: [S("isquiotibiais"), S("quadriceps"), S("core")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 2,
    estabilidade: "apoiado",
    perfilResistencia: "encurtado",
    equipamento: ["barra", "banco"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "alta",
  }),
  ex({
    id: "hip_thrust_maquina",
    nome: "Hip thrust na máquina",
    familia: "hip_extension",
    tier: 2,
    primarios: [P("gluteo")],
    secundarios: [S("isquiotibiais"), S("core")],
    fadigaSistemica: 1,
    fadigaLocal: 3,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "encurtado",
    equipamento: ["maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "alta",
  }),
  ex({
    id: "ponte_gluteo_barra",
    nome: "Ponte de glúteo com barra",
    familia: "hip_extension",
    tier: 3,
    primarios: [P("gluteo")],
    secundarios: [S("isquiotibiais")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "apoiado",
    perfilResistencia: "encurtado",
    equipamento: ["barra"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),
  ex({
    id: "hip_thrust_1_perna",
    nome: "Hip thrust a 1 perna",
    familia: "hip_extension",
    tier: 3,
    primarios: [P("gluteo")],
    secundarios: [S("isquiotibiais"), S("core")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 2,
    estabilidade: "apoiado",
    perfilResistencia: "encurtado",
    equipamento: ["peso_corporal", "halteres", "banco"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "baixa",
  }),
  ex({
    id: "kickback_cabo",
    nome: "Extensão de anca no cabo (kickback)",
    familia: "hip_extension",
    tier: 3,
    primarios: [P("gluteo")],
    secundarios: [S("isquiotibiais")],
    fadigaSistemica: 1,
    fadigaLocal: 1,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "encurtado",
    equipamento: ["cabos"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),
  ex({
    id: "abducao_anca_maquina",
    nome: "Abdução de anca na máquina",
    familia: "hip_extension",
    tier: 3,
    primarios: [P("gluteo")],
    secundarios: [],
    fadigaSistemica: 1,
    fadigaLocal: 1,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "encurtado",
    equipamento: ["maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),
  ex({
    id: "extensao_anca_45",
    nome: "Extensão de anca 45° (glute-ham raise parcial)",
    familia: "hip_extension",
    tier: 3,
    primarios: [P("gluteo"), P("isquiotibiais")],
    secundarios: [S("lombar")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 2,
    estabilidade: "apoiado",
    perfilResistencia: "alongado",
    equipamento: ["maquina"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["lombar"],
    progressao: "media",
  }),

  // =========================================================================
  // CALF — gémeos
  // =========================================================================
  ex({
    id: "gemeos_em_pe_maquina",
    nome: "Elevação de gémeos em pé (máquina)",
    familia: "calf",
    tier: 3,
    primarios: [P("gemeos")],
    secundarios: [],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "alongado",
    equipamento: ["maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["tornozelo"],
    progressao: "media",
  }),
  ex({
    id: "gemeos_sentado_maquina",
    nome: "Elevação de gémeos sentado (máquina)",
    familia: "calf",
    tier: 3,
    primarios: [P("gemeos")],
    secundarios: [],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "medio",
    equipamento: ["maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["tornozelo"],
    progressao: "media",
  }),
  ex({
    id: "gemeos_na_prensa",
    nome: "Elevação de gémeos na prensa",
    familia: "calf",
    tier: 3,
    primarios: [P("gemeos")],
    secundarios: [],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "alongado",
    equipamento: ["maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["tornozelo"],
    progressao: "alta",
  }),
  ex({
    id: "gemeos_1_perna_halter",
    nome: "Elevação de gémeos a 1 perna com halter",
    familia: "calf",
    tier: 3,
    primarios: [P("gemeos")],
    secundarios: [],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["halteres"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["tornozelo"],
    progressao: "baixa",
  }),

  // =========================================================================
  // HORIZONTAL PUSH — peito
  // =========================================================================
  ex({
    id: "supino_barra",
    nome: "Supino com barra",
    familia: "horizontal_push",
    tier: 1,
    primarios: [P("peito")],
    secundarios: [S("triceps"), S("deltoide_anterior")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["barra", "banco"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["ombro"],
    progressao: "alta",
  }),
  ex({
    id: "supino_halteres",
    nome: "Supino com halteres",
    familia: "horizontal_push",
    tier: 2,
    primarios: [P("peito")],
    secundarios: [S("triceps"), S("deltoide_anterior")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["halteres", "banco"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["ombro"],
    progressao: "media",
  }),
  ex({
    id: "chest_press_maquina",
    nome: "Supino na máquina (chest press)",
    familia: "horizontal_push",
    tier: 2,
    primarios: [P("peito")],
    secundarios: [S("triceps"), S("deltoide_anterior")],
    fadigaSistemica: 1,
    fadigaLocal: 3,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "medio",
    equipamento: ["maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "alta",
  }),
  ex({
    id: "supino_pegada_fechada",
    nome: "Supino pegada fechada",
    familia: "horizontal_push",
    padrao: "empurrar_horizontal",
    tier: 2,
    primarios: [P("peito")],
    secundarios: [S("triceps"), S("deltoide_anterior")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["barra", "banco"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["cotovelo", "pulso"],
    progressao: "alta",
  }),
  ex({
    id: "flexoes",
    nome: "Flexões",
    familia: "horizontal_push",
    tier: 3,
    primarios: [P("peito")],
    secundarios: [S("triceps"), S("deltoide_anterior"), S("core")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["peso_corporal"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["ombro", "pulso"],
    progressao: "baixa",
  }),
  ex({
    id: "flexoes_lastradas",
    nome: "Flexões lastradas",
    familia: "horizontal_push",
    tier: 2,
    primarios: [P("peito")],
    secundarios: [S("triceps"), S("deltoide_anterior"), S("core")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["peso_corporal"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["ombro", "pulso"],
    progressao: "media",
  }),
  ex({
    id: "floor_press",
    nome: "Floor press com halteres",
    familia: "horizontal_push",
    tier: 2,
    primarios: [P("peito")],
    secundarios: [S("triceps"), S("deltoide_anterior")],
    fadigaSistemica: 2,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "encurtado",
    equipamento: ["halteres"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),

  // =========================================================================
  // INCLINE PUSH — peito superior
  // =========================================================================
  ex({
    id: "supino_inclinado_barra",
    nome: "Supino inclinado com barra",
    familia: "incline_push",
    tier: 1,
    primarios: [P("peito")],
    secundarios: [S("deltoide_anterior"), S("triceps")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["barra", "banco"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["ombro"],
    progressao: "alta",
  }),
  ex({
    id: "supino_inclinado_halteres",
    nome: "Supino inclinado com halteres",
    familia: "incline_push",
    tier: 2,
    primarios: [P("peito")],
    secundarios: [S("deltoide_anterior"), S("triceps")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["halteres", "banco"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["ombro"],
    progressao: "media",
  }),
  ex({
    id: "press_inclinado_maquina",
    nome: "Press inclinado na máquina",
    familia: "incline_push",
    tier: 2,
    primarios: [P("peito")],
    secundarios: [S("deltoide_anterior"), S("triceps")],
    fadigaSistemica: 1,
    fadigaLocal: 3,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "medio",
    equipamento: ["maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "alta",
  }),
  ex({
    id: "supino_inclinado_smith",
    nome: "Supino inclinado no Smith",
    familia: "incline_push",
    tier: 2,
    primarios: [P("peito")],
    secundarios: [S("deltoide_anterior"), S("triceps")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 1,
    estabilidade: "apoiado",
    perfilResistencia: "medio",
    equipamento: ["maquina", "banco"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["ombro"],
    progressao: "alta",
  }),
  ex({
    id: "flexoes_pes_elevados",
    nome: "Flexões com pés elevados",
    familia: "incline_push",
    tier: 3,
    primarios: [P("peito")],
    secundarios: [S("deltoide_anterior"), S("triceps"), S("core")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["peso_corporal"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["ombro", "pulso"],
    progressao: "baixa",
  }),

  // =========================================================================
  // VERTICAL PUSH — deltoide (press)
  // =========================================================================
  ex({
    id: "press_militar_barra",
    nome: "Press militar em pé com barra",
    familia: "vertical_push",
    tier: 1,
    primarios: [P("deltoide_anterior")],
    secundarios: [S("deltoide_lateral"), S("triceps"), S("core"), S("trapezio_superior")],
    fadigaSistemica: 3,
    fadigaLocal: 3,
    exigenciaTecnica: 3,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["barra"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["ombro", "lombar", "pulso"],
    progressao: "alta",
  }),
  ex({
    id: "press_halteres_sentado",
    nome: "Press de ombros sentado com halteres",
    familia: "vertical_push",
    tier: 2,
    primarios: [P("deltoide_anterior")],
    secundarios: [S("deltoide_lateral"), S("triceps")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["halteres", "banco"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["ombro"],
    progressao: "media",
  }),
  ex({
    id: "press_arnold",
    nome: "Press Arnold",
    familia: "vertical_push",
    tier: 3,
    primarios: [P("deltoide_anterior")],
    secundarios: [S("deltoide_lateral"), S("triceps")],
    fadigaSistemica: 2,
    fadigaLocal: 2,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["halteres", "banco"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["ombro"],
    progressao: "media",
  }),
  ex({
    id: "push_press",
    nome: "Push press",
    familia: "vertical_push",
    padrao: "empurrar_vertical",
    tier: 2,
    primarios: [P("deltoide_anterior")],
    secundarios: [S("deltoide_lateral"), S("triceps"), S("quadriceps"), S("gluteo"), S("core")],
    fadigaSistemica: 3,
    fadigaLocal: 2,
    exigenciaTecnica: 3,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["barra"],
    nivelMinimo: "avancado",
    contraindicacoes: ["ombro", "lombar"],
    progressao: "alta",
  }),
  ex({
    id: "press_ombro_maquina",
    nome: "Press de ombros na máquina",
    familia: "vertical_push",
    tier: 2,
    primarios: [P("deltoide_anterior")],
    secundarios: [S("deltoide_lateral"), S("triceps")],
    fadigaSistemica: 1,
    fadigaLocal: 3,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "medio",
    equipamento: ["maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "alta",
  }),
  ex({
    id: "landmine_press",
    nome: "Landmine press",
    familia: "vertical_push",
    tier: 3,
    primarios: [P("deltoide_anterior")],
    secundarios: [S("peito"), S("triceps"), S("core")],
    fadigaSistemica: 2,
    fadigaLocal: 2,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["barra"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),

  // =========================================================================
  // CHEST ISOLATION
  // =========================================================================
  ex({
    id: "crossover_cabo_alto",
    nome: "Cross-over no cabo (polia alta)",
    familia: "chest_isolation",
    tier: 3,
    primarios: [P("peito")],
    secundarios: [S("deltoide_anterior")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "encurtado",
    equipamento: ["cabos"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["ombro"],
    progressao: "media",
  }),
  ex({
    id: "peck_deck",
    nome: "Peck deck (voador)",
    familia: "chest_isolation",
    tier: 3,
    primarios: [P("peito")],
    secundarios: [],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "encurtado",
    equipamento: ["maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["ombro"],
    progressao: "media",
  }),
  ex({
    id: "aberturas_halteres_inclinado",
    nome: "Aberturas com halteres em banco inclinado",
    familia: "chest_isolation",
    tier: 3,
    primarios: [P("peito")],
    secundarios: [S("deltoide_anterior")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["halteres", "banco"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["ombro"],
    progressao: "baixa",
  }),
  ex({
    id: "aberturas_maquina",
    nome: "Aberturas na máquina",
    familia: "chest_isolation",
    tier: 3,
    primarios: [P("peito")],
    secundarios: [],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "alongado",
    equipamento: ["maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["ombro"],
    progressao: "media",
  }),
  ex({
    id: "pullover_halter",
    nome: "Pullover com halter",
    familia: "chest_isolation",
    padrao: "empurrar_horizontal",
    tier: 3,
    primarios: [P("peito")],
    secundarios: [S("dorsais"), S("triceps"), S("core")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["halteres", "banco"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["ombro"],
    progressao: "baixa",
  }),

  // =========================================================================
  // VERTICAL PULL — dorsais
  // =========================================================================
  ex({
    id: "elevacoes_pronadas",
    nome: "Elevações (pega pronada)",
    familia: "vertical_pull",
    tier: 1,
    primarios: [P("dorsais")],
    secundarios: [S("biceps"), S("trapezio_medio"), S("antebraco"), S("core")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["barra_fixa"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["ombro", "cotovelo"],
    progressao: "media",
  }),
  ex({
    id: "chin_ups",
    nome: "Elevações supinadas (chin-ups)",
    familia: "vertical_pull",
    tier: 2,
    primarios: [P("dorsais")],
    secundarios: [S("biceps"), S("trapezio_medio"), S("antebraco"), S("core")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["barra_fixa"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["cotovelo", "ombro"],
    progressao: "media",
  }),
  ex({
    id: "pulldown_barra",
    nome: "Puxada na barra (pulldown)",
    familia: "vertical_pull",
    tier: 2,
    primarios: [P("dorsais")],
    secundarios: [S("biceps"), S("trapezio_medio"), S("deltoide_posterior")],
    fadigaSistemica: 1,
    fadigaLocal: 3,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "medio",
    equipamento: ["maquina", "cabos"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "alta",
  }),
  ex({
    id: "pulldown_pega_neutra",
    nome: "Puxada com pega neutra",
    familia: "vertical_pull",
    tier: 2,
    primarios: [P("dorsais")],
    secundarios: [S("biceps"), S("trapezio_medio"), S("antebraco")],
    fadigaSistemica: 1,
    fadigaLocal: 3,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "medio",
    equipamento: ["maquina", "cabos"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "alta",
  }),
  ex({
    id: "pulldown_1_braco_cabo",
    nome: "Puxada a 1 braço no cabo",
    familia: "vertical_pull",
    tier: 3,
    primarios: [P("dorsais")],
    secundarios: [S("biceps"), S("core")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["cabos"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),
  ex({
    id: "pullover_cabo",
    nome: "Pullover no cabo (polia alta)",
    familia: "vertical_pull",
    tier: 3,
    primarios: [P("dorsais")],
    secundarios: [S("triceps"), S("peito")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["cabos"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),

  // =========================================================================
  // HORIZONTAL PULL — costas médias
  // =========================================================================
  ex({
    id: "remada_curvada_barra",
    nome: "Remada curvada com barra",
    familia: "horizontal_pull",
    tier: 1,
    primarios: [P("dorsais")],
    secundarios: [S("trapezio_medio"), S("biceps"), S("deltoide_posterior"), S("lombar"), S("antebraco")],
    fadigaSistemica: 3,
    fadigaLocal: 3,
    exigenciaTecnica: 3,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["barra"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["lombar"],
    progressao: "alta",
  }),
  ex({
    id: "remada_pendlay",
    nome: "Remada Pendlay",
    familia: "horizontal_pull",
    tier: 1,
    primarios: [P("dorsais")],
    secundarios: [S("trapezio_medio"), S("biceps"), S("deltoide_posterior"), S("lombar")],
    fadigaSistemica: 3,
    fadigaLocal: 3,
    exigenciaTecnica: 3,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["barra"],
    nivelMinimo: "avancado",
    contraindicacoes: ["lombar"],
    progressao: "alta",
  }),
  ex({
    id: "remada_halter_1_braco",
    nome: "Remada com halter a 1 braço",
    familia: "horizontal_pull",
    tier: 2,
    primarios: [P("dorsais")],
    secundarios: [S("trapezio_medio"), S("biceps"), S("deltoide_posterior"), S("core")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 1,
    estabilidade: "apoiado",
    perfilResistencia: "alongado",
    equipamento: ["halteres", "banco"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),
  ex({
    id: "remada_sentada_cabo",
    nome: "Remada sentada no cabo",
    familia: "horizontal_pull",
    tier: 2,
    primarios: [P("dorsais")],
    secundarios: [S("trapezio_medio"), S("biceps"), S("deltoide_posterior")],
    fadigaSistemica: 1,
    fadigaLocal: 3,
    exigenciaTecnica: 1,
    estabilidade: "apoiado",
    perfilResistencia: "medio",
    equipamento: ["cabos", "maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "alta",
  }),
  ex({
    id: "remada_maquina_apoiada",
    nome: "Remada apoiada no peito (chest-supported)",
    familia: "horizontal_pull",
    tier: 2,
    primarios: [P("dorsais")],
    secundarios: [S("trapezio_medio"), S("biceps"), S("deltoide_posterior")],
    fadigaSistemica: 1,
    fadigaLocal: 3,
    exigenciaTecnica: 1,
    estabilidade: "apoiado",
    perfilResistencia: "medio",
    equipamento: ["maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "alta",
  }),
  ex({
    id: "remada_t_bar",
    nome: "Remada T-bar",
    familia: "horizontal_pull",
    tier: 2,
    primarios: [P("dorsais")],
    secundarios: [S("trapezio_medio"), S("biceps"), S("lombar"), S("deltoide_posterior")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 2,
    estabilidade: "apoiado",
    perfilResistencia: "medio",
    equipamento: ["barra", "maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["lombar"],
    progressao: "alta",
  }),
  ex({
    id: "remada_invertida",
    nome: "Remada invertida (peso corporal)",
    familia: "horizontal_pull",
    tier: 3,
    primarios: [P("dorsais")],
    secundarios: [S("trapezio_medio"), S("biceps"), S("core"), S("deltoide_posterior")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["barra_fixa", "trx"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "baixa",
  }),

  // =========================================================================
  // REAR DELT / SCAP
  // =========================================================================
  ex({
    id: "crucifixo_invertido_halteres",
    nome: "Crucifixo invertido com halteres",
    familia: "rear_delt_scap",
    tier: 3,
    primarios: [P("deltoide_posterior")],
    secundarios: [S("trapezio_medio")],
    fadigaSistemica: 1,
    fadigaLocal: 1,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "encurtado",
    equipamento: ["halteres"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "baixa",
  }),
  ex({
    id: "reverse_peck_deck",
    nome: "Crucifixo invertido na máquina (reverse peck deck)",
    familia: "rear_delt_scap",
    tier: 3,
    primarios: [P("deltoide_posterior")],
    secundarios: [S("trapezio_medio")],
    fadigaSistemica: 1,
    fadigaLocal: 1,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "encurtado",
    equipamento: ["maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),
  ex({
    id: "face_pull_corda",
    nome: "Face pull com corda",
    familia: "rear_delt_scap",
    tier: 3,
    primarios: [P("deltoide_posterior")],
    secundarios: [S("trapezio_medio")],
    fadigaSistemica: 1,
    fadigaLocal: 1,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["cabos"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),
  ex({
    id: "band_pull_apart",
    nome: "Band pull-apart",
    familia: "rear_delt_scap",
    tier: 3,
    primarios: [P("deltoide_posterior")],
    secundarios: [S("trapezio_medio")],
    fadigaSistemica: 1,
    fadigaLocal: 1,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "encurtado",
    equipamento: ["banda"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "baixa",
  }),

  // =========================================================================
  // LATERAL RAISE — deltoide lateral
  // =========================================================================
  ex({
    id: "elevacao_lateral_halteres",
    nome: "Elevação lateral com halteres",
    familia: "lateral_raise",
    tier: 3,
    primarios: [P("deltoide_lateral")],
    secundarios: [S("trapezio_superior")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["halteres"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["ombro"],
    progressao: "baixa",
  }),
  ex({
    id: "elevacao_lateral_cabo",
    nome: "Elevação lateral no cabo",
    familia: "lateral_raise",
    tier: 3,
    primarios: [P("deltoide_lateral")],
    secundarios: [],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["cabos"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["ombro"],
    progressao: "media",
  }),
  ex({
    id: "elevacao_lateral_maquina",
    nome: "Elevação lateral na máquina",
    familia: "lateral_raise",
    tier: 3,
    primarios: [P("deltoide_lateral")],
    secundarios: [],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "encurtado",
    equipamento: ["maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),
  ex({
    id: "elevacao_lateral_inclinado",
    nome: "Elevação lateral inclinado (lean-away)",
    familia: "lateral_raise",
    tier: 3,
    primarios: [P("deltoide_lateral")],
    secundarios: [],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["halteres"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["ombro"],
    progressao: "baixa",
  }),
  ex({
    id: "upright_row_cabo",
    nome: "Remada alta no cabo (pega larga)",
    familia: "lateral_raise",
    padrao: "abducao_ombro",
    tier: 3,
    primarios: [P("deltoide_lateral")],
    secundarios: [S("trapezio_superior"), S("biceps")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["cabos"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["ombro"],
    progressao: "media",
  }),

  // =========================================================================
  // TRAPÉZIO — encolhimentos
  // =========================================================================
  ex({
    id: "encolhimento_barra",
    nome: "Encolhimento de ombros com barra",
    familia: "trapezio",
    tier: 3,
    primarios: [P("trapezio_superior")],
    secundarios: [S("antebraco")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "encurtado",
    equipamento: ["barra"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["pescoco"],
    progressao: "alta",
  }),
  ex({
    id: "encolhimento_halteres",
    nome: "Encolhimento de ombros com halteres",
    familia: "trapezio",
    tier: 3,
    primarios: [P("trapezio_superior")],
    secundarios: [S("antebraco")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["halteres"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["pescoco"],
    progressao: "media",
  }),
  ex({
    id: "encolhimento_maquina",
    nome: "Encolhimento na máquina / trap-bar",
    familia: "trapezio",
    tier: 3,
    primarios: [P("trapezio_superior")],
    secundarios: [],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "medio",
    equipamento: ["maquina", "barra"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["pescoco"],
    progressao: "alta",
  }),

  // =========================================================================
  // ELBOW FLEXION — bíceps
  // =========================================================================
  ex({
    id: "rosca_direta_barra",
    nome: "Rosca direta com barra",
    familia: "elbow_flexion",
    tier: 3,
    primarios: [P("biceps")],
    secundarios: [S("antebraco")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["barra"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["pulso", "cotovelo"],
    progressao: "media",
  }),
  ex({
    id: "rosca_barra_w",
    nome: "Rosca com barra W",
    familia: "elbow_flexion",
    tier: 3,
    primarios: [P("biceps")],
    secundarios: [S("antebraco")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["barra"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["cotovelo"],
    progressao: "media",
  }),
  ex({
    id: "rosca_halteres_alternada",
    nome: "Rosca com halteres alternada",
    familia: "elbow_flexion",
    tier: 3,
    primarios: [P("biceps")],
    secundarios: [S("antebraco")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["halteres"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "baixa",
  }),
  ex({
    id: "rosca_martelo",
    nome: "Rosca martelo",
    familia: "elbow_flexion",
    tier: 3,
    primarios: [P("biceps")],
    secundarios: [S("antebraco")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["halteres"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "baixa",
  }),
  ex({
    id: "rosca_scott",
    nome: "Rosca Scott (banco preacher)",
    familia: "elbow_flexion",
    tier: 3,
    primarios: [P("biceps")],
    secundarios: [S("antebraco")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "apoiado",
    perfilResistencia: "alongado",
    equipamento: ["maquina"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["cotovelo"],
    progressao: "media",
  }),
  ex({
    id: "rosca_inclinado_halteres",
    nome: "Rosca inclinado com halteres",
    familia: "elbow_flexion",
    tier: 3,
    primarios: [P("biceps")],
    secundarios: [],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "apoiado",
    perfilResistencia: "alongado",
    equipamento: ["halteres", "banco"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "baixa",
  }),
  ex({
    id: "rosca_cabo",
    nome: "Rosca no cabo (polia baixa)",
    familia: "elbow_flexion",
    tier: 3,
    primarios: [P("biceps")],
    secundarios: [S("antebraco")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "encurtado",
    equipamento: ["cabos"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),

  // =========================================================================
  // ELBOW EXTENSION — tríceps
  // =========================================================================
  ex({
    id: "triceps_pushdown_corda",
    nome: "Tríceps no cabo com corda (pushdown)",
    familia: "elbow_extension",
    tier: 3,
    primarios: [P("triceps")],
    secundarios: [],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "encurtado",
    equipamento: ["cabos"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),
  ex({
    id: "triceps_testa_barra",
    nome: "Tríceps testa com barra",
    familia: "elbow_extension",
    tier: 3,
    primarios: [P("triceps")],
    secundarios: [],
    fadigaSistemica: 1,
    fadigaLocal: 3,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["barra", "banco"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["cotovelo"],
    progressao: "media",
  }),
  ex({
    id: "triceps_testa_halteres",
    nome: "Tríceps testa com halteres",
    familia: "elbow_extension",
    tier: 3,
    primarios: [P("triceps")],
    secundarios: [],
    fadigaSistemica: 1,
    fadigaLocal: 3,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["halteres", "banco"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["cotovelo"],
    progressao: "baixa",
  }),
  ex({
    id: "extensao_triceps_overhead_cabo",
    nome: "Extensão de tríceps por cima da cabeça (cabo)",
    familia: "elbow_extension",
    tier: 3,
    primarios: [P("triceps")],
    secundarios: [],
    fadigaSistemica: 1,
    fadigaLocal: 3,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["cabos"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["ombro"],
    progressao: "media",
  }),
  ex({
    id: "extensao_triceps_overhead_halter",
    nome: "Extensão de tríceps por cima da cabeça (halter)",
    familia: "elbow_extension",
    tier: 3,
    primarios: [P("triceps")],
    secundarios: [],
    fadigaSistemica: 1,
    fadigaLocal: 3,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["halteres"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["ombro"],
    progressao: "baixa",
  }),
  ex({
    id: "fundos_paralelas",
    nome: "Fundos nas paralelas",
    familia: "elbow_extension",
    padrao: "extensao_cotovelo",
    tier: 2,
    primarios: [P("triceps")],
    secundarios: [S("peito"), S("deltoide_anterior")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["paralelas"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["ombro", "cotovelo"],
    progressao: "media",
  }),

  // =========================================================================
  // CORE
  // =========================================================================
  ex({
    id: "prancha",
    nome: "Prancha frontal",
    familia: "core",
    padrao: "core_antiextensao",
    tier: 3,
    primarios: [P("core")],
    secundarios: [],
    fadigaSistemica: 1,
    fadigaLocal: 1,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "encurtado",
    equipamento: ["peso_corporal"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "baixa",
  }),
  ex({
    id: "ab_rollout",
    nome: "Rollout com roda abdominal",
    familia: "core",
    padrao: "core_antiextensao",
    tier: 2,
    primarios: [P("core")],
    secundarios: [S("dorsais"), S("lombar")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["peso_corporal"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["lombar"],
    progressao: "baixa",
  }),
  ex({
    id: "pallof_press",
    nome: "Pallof press",
    familia: "core",
    padrao: "core_antirrotacao",
    tier: 3,
    primarios: [P("core")],
    secundarios: [],
    fadigaSistemica: 1,
    fadigaLocal: 1,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["banda", "cabos"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),
  ex({
    id: "elevacao_pernas_suspensa",
    nome: "Elevação de pernas suspensa",
    familia: "core",
    padrao: "core_flexao",
    tier: 3,
    primarios: [P("core")],
    secundarios: [S("antebraco")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["barra_fixa"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["lombar"],
    progressao: "baixa",
  }),
  ex({
    id: "crunch_cabo",
    nome: "Crunch no cabo (ajoelhado)",
    familia: "core",
    padrao: "core_flexao",
    tier: 3,
    primarios: [P("core")],
    secundarios: [],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "encurtado",
    equipamento: ["cabos"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),
  ex({
    id: "prancha_lateral",
    nome: "Prancha lateral",
    familia: "core",
    padrao: "core_antirrotacao",
    tier: 3,
    primarios: [P("core")],
    secundarios: [S("gluteo")],
    fadigaSistemica: 1,
    fadigaLocal: 1,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "encurtado",
    equipamento: ["peso_corporal"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "baixa",
  }),

  // =========================================================================
  // CARRY — transporte
  // =========================================================================
  ex({
    id: "farmers_carry",
    nome: "Farmer's carry",
    familia: "carry",
    tier: 2,
    primarios: [P("antebraco"), P("core"), P("trapezio_superior")],
    secundarios: [S("gluteo"), S("quadriceps")],
    fadigaSistemica: 2,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "encurtado",
    equipamento: ["halteres", "kettlebell"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "alta",
  }),
  ex({
    id: "suitcase_carry",
    nome: "Suitcase carry (1 lado)",
    familia: "carry",
    padrao: "core_antirrotacao",
    tier: 3,
    primarios: [P("core"), P("antebraco")],
    secundarios: [S("gluteo"), S("trapezio_superior")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "encurtado",
    equipamento: ["halteres", "kettlebell"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),
  ex({
    id: "sandbag_carry_frontal",
    nome: "Transporte frontal de saco (Zercher/sandbag)",
    familia: "carry",
    tier: 3,
    primarios: [P("core"), P("lombar")],
    secundarios: [S("quadriceps"), S("trapezio_superior"), S("antebraco")],
    fadigaSistemica: 2,
    fadigaLocal: 2,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["kettlebell"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["lombar"],
    progressao: "media",
  }),

  // =========================================================================
  // CONDITIONING — potência / circuitos
  // =========================================================================
  ex({
    id: "kb_swing",
    nome: "Kettlebell swing",
    familia: "conditioning",
    padrao: "dobrar_anca",
    tier: 2,
    primarios: [P("gluteo"), P("isquiotibiais")],
    secundarios: [S("core"), S("lombar"), S("deltoide_anterior"), S("cardio")],
    fadigaSistemica: 2,
    fadigaLocal: 2,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["kettlebell"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["lombar"],
    progressao: "media",
  }),
  ex({
    id: "wall_ball",
    nome: "Wall ball",
    familia: "conditioning",
    tier: 2,
    primarios: [P("quadriceps"), P("deltoide_anterior")],
    secundarios: [S("gluteo"), S("triceps"), S("cardio"), S("core")],
    fadigaSistemica: 2,
    fadigaLocal: 2,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["wall_ball"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["joelho", "ombro"],
    progressao: "baixa",
  }),
  ex({
    id: "sled_push",
    nome: "Sled push",
    familia: "conditioning",
    padrao: "locomocao",
    tier: 2,
    primarios: [P("quadriceps"), P("gluteo")],
    secundarios: [S("gemeos"), S("cardio"), S("core")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "encurtado",
    equipamento: ["sled"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "alta",
  }),
  ex({
    id: "sled_pull",
    nome: "Sled pull",
    familia: "conditioning",
    padrao: "puxar_horizontal",
    tier: 2,
    primarios: [P("dorsais"), P("isquiotibiais")],
    secundarios: [S("biceps"), S("gluteo"), S("cardio")],
    fadigaSistemica: 2,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["sled"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "alta",
  }),
  ex({
    id: "thruster",
    nome: "Thruster (agachamento + press)",
    familia: "conditioning",
    tier: 2,
    primarios: [P("quadriceps"), P("deltoide_anterior")],
    secundarios: [S("gluteo"), S("triceps"), S("core"), S("cardio")],
    fadigaSistemica: 3,
    fadigaLocal: 3,
    exigenciaTecnica: 3,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["barra", "halteres"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["ombro", "joelho", "lombar"],
    progressao: "media",
  }),
  ex({
    id: "burpee",
    nome: "Burpee",
    familia: "conditioning",
    tier: 3,
    primarios: [P("cardio")],
    secundarios: [S("peito"), S("quadriceps"), S("core")],
    fadigaSistemica: 2,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["peso_corporal"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["ombro", "pulso"],
    progressao: "baixa",
  }),
  ex({
    id: "box_jump",
    nome: "Box jump",
    familia: "conditioning",
    padrao: "potencia",
    tier: 3,
    primarios: [P("quadriceps"), P("gluteo")],
    secundarios: [S("gemeos"), S("isquiotibiais")],
    fadigaSistemica: 2,
    fadigaLocal: 2,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["caixa"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["joelho", "tornozelo"],
    progressao: "baixa",
  }),
  ex({
    id: "assault_bike_sprint",
    nome: "Sprint na assault bike",
    familia: "conditioning",
    padrao: "locomocao",
    tier: 3,
    primarios: [P("cardio")],
    secundarios: [S("quadriceps"), S("deltoide_anterior")],
    fadigaSistemica: 3,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "medio",
    equipamento: ["bicicleta"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "alta",
  }),

  // =========================================================================
  // CARDIO — Z2 e intervalos (spec 2.5 e 2.6)
  // =========================================================================
  ex({
    id: "corrida_z2",
    nome: "Corrida contínua Zona 2",
    familia: "cardio",
    tier: 1,
    primarios: [P("cardio")],
    secundarios: [S("quadriceps"), S("isquiotibiais"), S("gemeos")],
    fadigaSistemica: 2,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["passadeira", "peso_corporal"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["joelho", "tornozelo"],
    progressao: "media",
  }),
  ex({
    id: "corrida_intervalos_vo2",
    nome: "Corrida em intervalos (VO₂max)",
    familia: "cardio",
    padrao: "locomocao",
    tier: 1,
    primarios: [P("cardio")],
    secundarios: [S("quadriceps"), S("isquiotibiais"), S("gemeos")],
    fadigaSistemica: 3,
    fadigaLocal: 3,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["passadeira", "peso_corporal"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["joelho", "tornozelo"],
    progressao: "media",
  }),
  ex({
    id: "corrida_tempo_limiar",
    nome: "Corrida em ritmo de limiar (tempo)",
    familia: "cardio",
    padrao: "locomocao",
    tier: 2,
    primarios: [P("cardio")],
    secundarios: [S("quadriceps"), S("isquiotibiais")],
    fadigaSistemica: 2,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["passadeira", "peso_corporal"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["joelho"],
    progressao: "media",
  }),
  ex({
    id: "bicicleta_z2",
    nome: "Bicicleta Zona 2",
    familia: "cardio",
    tier: 1,
    primarios: [P("cardio")],
    secundarios: [S("quadriceps")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "medio",
    equipamento: ["bicicleta"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),
  ex({
    id: "bicicleta_intervalos",
    nome: "Bicicleta em intervalos",
    familia: "cardio",
    padrao: "locomocao",
    tier: 2,
    primarios: [P("cardio")],
    secundarios: [S("quadriceps"), S("gluteo")],
    fadigaSistemica: 2,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "medio",
    equipamento: ["bicicleta"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),
  ex({
    id: "remo_ergometro_z2",
    nome: "Remo no ergómetro Zona 2",
    familia: "cardio",
    tier: 1,
    primarios: [P("cardio")],
    secundarios: [S("dorsais"), S("quadriceps"), S("core")],
    fadigaSistemica: 2,
    fadigaLocal: 2,
    exigenciaTecnica: 2,
    estabilidade: "maquina",
    perfilResistencia: "medio",
    equipamento: ["remo_ergometro"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["lombar"],
    progressao: "media",
  }),
  ex({
    id: "remo_ergometro_intervalos",
    nome: "Remo no ergómetro em intervalos",
    familia: "cardio",
    padrao: "locomocao",
    tier: 2,
    primarios: [P("cardio")],
    secundarios: [S("dorsais"), S("quadriceps")],
    fadigaSistemica: 3,
    fadigaLocal: 2,
    exigenciaTecnica: 2,
    estabilidade: "maquina",
    perfilResistencia: "medio",
    equipamento: ["remo_ergometro"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["lombar"],
    progressao: "media",
  }),
  ex({
    id: "skierg_intervalos",
    nome: "SkiErg em intervalos",
    familia: "cardio",
    padrao: "locomocao",
    tier: 3,
    primarios: [P("cardio")],
    secundarios: [S("dorsais"), S("triceps"), S("core")],
    fadigaSistemica: 2,
    fadigaLocal: 2,
    exigenciaTecnica: 1,
    estabilidade: "maquina",
    perfilResistencia: "medio",
    equipamento: ["skierg"],
    nivelMinimo: "iniciante",
    contraindicacoes: [],
    progressao: "media",
  }),

  // =========================================================================
  // SKILL — calistenia
  // =========================================================================
  ex({
    id: "handstand_progressao",
    nome: "Progressão para pino (handstand)",
    familia: "skill",
    padrao: "empurrar_vertical",
    tier: 2,
    primarios: [P("deltoide_anterior")],
    secundarios: [S("deltoide_lateral"), S("triceps"), S("core"), S("trapezio_superior")],
    fadigaSistemica: 2,
    fadigaLocal: 2,
    exigenciaTecnica: 3,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["peso_corporal"],
    nivelMinimo: "intermedio",
    contraindicacoes: ["ombro", "pulso", "pescoco"],
    progressao: "baixa",
  }),
  ex({
    id: "l_sit",
    nome: "L-sit",
    familia: "skill",
    padrao: "core_flexao",
    tier: 3,
    primarios: [P("core")],
    secundarios: [S("quadriceps"), S("triceps"), S("deltoide_anterior")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 3,
    estabilidade: "livre",
    perfilResistencia: "encurtado",
    equipamento: ["paralelas", "peso_corporal"],
    nivelMinimo: "intermedio",
    contraindicacoes: [],
    progressao: "baixa",
  }),
  ex({
    id: "muscle_up_progressao",
    nome: "Progressão para muscle-up",
    familia: "skill",
    padrao: "puxar_vertical",
    tier: 2,
    primarios: [P("dorsais"), P("triceps")],
    secundarios: [S("biceps"), S("peito"), S("core")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 3,
    estabilidade: "livre",
    perfilResistencia: "medio",
    equipamento: ["barra_fixa"],
    nivelMinimo: "avancado",
    contraindicacoes: ["ombro", "cotovelo", "pulso"],
    progressao: "baixa",
  }),
  ex({
    id: "front_lever_progressao",
    nome: "Progressão para front lever",
    familia: "skill",
    padrao: "puxar_horizontal",
    tier: 2,
    primarios: [P("dorsais"), P("core")],
    secundarios: [S("biceps"), S("lombar")],
    fadigaSistemica: 2,
    fadigaLocal: 3,
    exigenciaTecnica: 3,
    estabilidade: "livre",
    perfilResistencia: "encurtado",
    equipamento: ["barra_fixa"],
    nivelMinimo: "avancado",
    contraindicacoes: ["ombro", "cotovelo"],
    progressao: "baixa",
  }),
  ex({
    id: "pike_push_up",
    nome: "Pike push-up",
    familia: "skill",
    padrao: "empurrar_vertical",
    tier: 3,
    primarios: [P("deltoide_anterior")],
    secundarios: [S("deltoide_lateral"), S("triceps"), S("core")],
    fadigaSistemica: 1,
    fadigaLocal: 2,
    exigenciaTecnica: 2,
    estabilidade: "livre",
    perfilResistencia: "alongado",
    equipamento: ["peso_corporal"],
    nivelMinimo: "iniciante",
    contraindicacoes: ["ombro", "pulso"],
    progressao: "baixa",
  }),
];
